### ISSUE TITLE
error installing

### ISSUE THREAD

**Issue by andrewljohnson** [lacker/coinkit#8]
When I try to do the go get, I get an error related to healthz.

```
➜  coinkit git:(master) go get -t ./...               
# coinkit/cmd/cserver
```

cmd/cserver/main.go:62: s.ServeHealthzInBackground undefined (type *network.Server has no field or method ServeHealthzInBackground)

**Comment by lacker** [comment]
Oops, I broke that this morning. Should be fixed now, thanks for finding it
